# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10738b3821b3af78b162889a6a7aae6babb5de7a604f1cab5c2001dbb9405b081d0c36c9b85f31782c3a8bebf36522c96204fe76de01359b0ed4db07fcd85d95
  api_key: a1B2c3D4e5F6
test:
  secret_key_base: d127649602a3147e2ec892bf2be18309abf7b962af42cc04637584d5a8fe07817da1db8b47cb536440de38c6b718d1529c66ac0e70ee812fb28d3cdb4b2182a6
  api_key: wZ5kgFTBJYleu1VXFzrW
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
